---
display:
  model: "2.13inch e-Paper HAT"
  version: "V4"
  driver: epd2in13_V4
  
  dimensions:
    width: 122
    height: 250
  
  refresh:
    full_update_init: no_parameter
    supports_partial: false
