# ============================================
# E-Paper Display Hardware Configuration
# ============================================
# This file contains hardware-specific settings
# that rarely need to be changed after initial setup
# ============================================

# Display hardware specifications
display:
  # Display type/driver
  # Options: waveshare_2in13_v2, waveshare_2in13_v3, waveshare_4in2, inky_phat
  type: "waveshare_2in13_v2"
  
  # Display dimensions in pixels
  width: 250
  height: 122
  
  # Display orientation
  # Options: horizontal, vertical
  orientation: "horizontal"
  
  # Color mode
  # Options: bw (black/white), bwr (black/white/red), bwy (black/white/yellow)
  color_mode: "bw"
  
  # Display refresh rate
  # Options: full (slower, cleaner), partial (faster, may ghost)
  default_refresh: "full"

# ============================================
# Power Management
# ============================================
power_management:
  # Put display in deep sleep mode between updates?
  # Saves significant power but adds ~2s wake-up time
  sleep_between_updates: true
  
  # How often to do a full display clear (prevents ghosting)
  # Lower number = less ghosting, more power use
  # Higher number = more power efficient, possible ghosting
  full_clear_interval: 10
  
  # Seconds to wait after display update before sleeping
  # Gives display time to stabilize
  sleep_delay: 2
  
  # Enable aggressive power saving?
  # Disables WiFi between updates (requires PiSugar button wake)
  aggressive_power_save: false

# ============================================
# Image Processing Pipeline
# ============================================
image_processing:
  # Contrast enhancement factor
  # 1.0 = no change, 1.2 = 20% more contrast (recommended)
  # Higher values make images "punchier" but can lose detail
  contrast_enhancement: 1.2
  
  # Brightness adjustment
  # 1.0 = no change, 1.1 = 10% brighter, 0.9 = 10% darker
  brightness_adjustment: 1.0
  
  # Sharpness enhancement
  # 1.0 = no change, 1.2 = 20% sharper
  # Can make dithered images look better
  sharpness_enhancement: 1.0
  
  # Dithering algorithm for converting to black/white
  # Options:
  #   - floyd-steinberg: Best quality, natural appearance (recommended)
  #   - ordered: Faster, more regular pattern
  #   - threshold: Fastest, harsh contrast
  dithering: "floyd-steinberg"
  
  # Image resampling quality when resizing
  # Options: nearest, bilinear, bicubic, lanczos (highest quality)
  resampling: "lanczos"
  
  # Add border around images?
  border: true
  
  # Border width in pixels
  border_width: 1
  
  # Border color (0 = black, 255 = white)
  border_color: 0

# ============================================
# Display Calibration
# ============================================
calibration:
  # Gamma correction (adjusts mid-tones)
  # 1.0 = no change, <1.0 = darker, >1.0 = lighter
  gamma: 1.0
  
  # Temperature compensation (if display supports it)
  # Some e-paper displays behave differently at different temps
  enable_temperature_compensation: false
  
  # Voltage adjustment (advanced, usually leave at default)
  # Affects how "dark" the blacks are
  voltage_adjustment: 0

# ============================================
# Performance Settings
# ============================================
performance:
  # Enable multi-threading for image processing?
  # Speeds up processing on Pi Zero 2 W (4 cores)
  enable_multithreading: true
  
  # Number of worker threads (0 = auto-detect)
  worker_threads: 0
  
  # Cache processed images?
  # Speeds up re-displaying but uses more memory
  enable_cache: false
  
  # Cache size in MB
  cache_size_mb: 10

# ============================================
# Hardware-Specific Quirks
# ============================================
hardware_quirks:
  # Some displays need extra initialization time
  init_delay_ms: 100
  
  # Some displays need a "dummy" refresh on startup
  dummy_refresh_on_init: false
  
  # GPIO pin assignments (only change if using custom wiring)
  gpio_pins:
    rst: 17   # GPIO 17 (physical pin 11)
    dc: 25    # GPIO 25 (physical pin 22)
    cs: 8     # GPIO 8 (physical pin 24)
    busy: 24  # GPIO 24 (physical pin 18)