---
frame:
  photo_directory: /home/pi/pictures
  refresh_interval: 300
  random_order: true
  supported_formats:
    - .jpg
    - .jpeg
    - .png
    - .bmp

display:
  width: 122
  height: 250
  image_processing:
    contrast_enhancement: 1.2
    add_border: true
    border_width: 1
  power_management:
    sleep_between_updates: true
    full_clear_interval: 10

logging:
  file: /home/pi/logs/picture_frame.log
  level: INFO
