# ============================================
# E-Paper Picture Frame Behavior Configuration
# ============================================
# This file controls how the picture frame behaves
# Edit these settings to customize your frame
# ============================================

# Core frame behavior
frame:
  # How often to change photos (in seconds)
  # Examples: 60 = 1 min, 300 = 5 min, 600 = 10 min, 3600 = 1 hour
  refresh_interval: 300
  
  # Display photos in random order or sequential?
  # true = random, false = alphabetical order
  random_order: true
  
  # Show startup message when frame starts?
  startup_message: true
  
  # Startup message duration (seconds)
  startup_duration: 3
  
  # Photo directory path
  # This is where the frame looks for images
  photo_directory: "/home/pi/pictures"
  
  # Supported image file formats
  # Add or remove formats as needed
  supported_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".bmp"
    - ".gif"  # Animated GIFs show first frame only
  
  # Subdirectory handling
  # Options: ignore, include, separate
  #   - ignore: Only show photos in root photo_directory
  #   - include: Show photos from all subdirectories
  #   - separate: Cycle through one subdirectory at a time
  subdirectory_mode: "include"

# ============================================
# Display Options
# ============================================
display_options:
  # Show filename at bottom of photo?
  show_filename: false
  
  # Show timestamp when photo was taken (from EXIF)?
  show_timestamp: false
  
  # Show photo index (e.g., "3 / 42")?
  show_index: false
  
  # Show battery percentage (requires PiSugar)?
  show_battery: false
  
  # Position of overlay text
  # Options: top-left, top-right, bottom-left, bottom-right
  overlay_position: "bottom-left"
  
  # Overlay text size (small, medium, large)
  overlay_size: "small"
  
  # Overlay background (makes text easier to read)
  # Options: none, translucent, solid
  overlay_background: "solid"

# ============================================
# Image Selection & Filtering
# ============================================
image_selection:
  # Minimum image dimensions (pixels)
  # Images smaller than this are skipped
  min_width: 100
  min_height: 100
  
  # Skip images with specific words in filename?
  exclude_patterns:
    - "screenshot"
    - "temp"
    - "draft"
  
  # Only include images with specific words?
  # Leave empty to include all (default)
  include_patterns: []
  
  # Sort method when random_order is false
  # Options: name, date_taken, date_modified, size
  sort_by: "name"
  
  # Sort direction
  # Options: ascending, descending
  sort_direction: "ascending"
  
  # Rescan directory for new images?
  # Options: never, each_cycle, hourly, daily
  rescan_mode: "each_cycle"

# ============================================
# Photo Metadata (EXIF)
# ============================================
metadata:
  # Extract and use EXIF data from photos?
  use_exif: true
  
  # Auto-rotate photos based on EXIF orientation?
  auto_rotate: true
  
  # Prefer EXIF thumbnail for faster loading?
  # Only works for very small displays
  use_embedded_thumbnail: false

# ============================================
# Transitions (if supported by display)
# ============================================
transitions:
  # Enable transition effects between photos?
  # Only works with displays that support partial refresh
  enabled: false
  
  # Transition type
  # Options: fade, wipe, dissolve
  type: "fade"
  
  # Transition duration (seconds)
  duration: 2

# ============================================
# Schedule (Time-based behavior)
# ============================================
schedule:
  # Enable scheduled on/off times?
  enabled: false
  
  # Turn on time (24-hour format)
  turn_on_time: "07:00"
  
  # Turn off time (24-hour format)
  turn_off_time: "22:00"
  
  # Days of week to operate
  # Options: all, weekdays, weekends, or specific days
  active_days: "all"
  # Example for specific days:
  # active_days: ["monday", "wednesday", "friday"]
  
  # What to display when "off"?
  # Options: blank, clock, message
  off_display: "blank"
  
  # Message to show when off (if off_display = message)
  off_message: "Good night!"

# ============================================
# Logging Configuration
# ============================================
logging:
  # Log level
  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  # DEBUG = very verbose, CRITICAL = only severe errors
  level: "INFO"
  
  # Log file location
  file: "/home/pi/picture_frame.log"
  
  # Maximum log file size (bytes)
  # When reached, old logs are archived
  max_bytes: 1048576  # 1 MB
  
  # Number of archived log files to keep
  backup_count: 3
  
  # Log rotation
  # Options: size (rotate when max_bytes reached), daily, weekly
  rotation: "size"
  
  # Include timestamps in console output?
  console_timestamps: false

# ============================================
# Network Features
# ============================================
network:
  # Enable web-based photo upload interface?
  enable_web_upload: false
  
  # Web server port
  web_port: 8080
  
  # Require authentication for uploads?
  require_auth: true
  
  # Upload username (if require_auth = true)
  upload_username: "admin"
  
  # Upload password (if require_auth = true)
  # CHANGE THIS DEFAULT PASSWORD!
  upload_password: "changeme"
  
  # Enable remote API for control?
  enable_api: false
  
  # API port
  api_port: 8081
  
  # API authentication token
  api_token: "your-secret-token-here"

# ============================================
# Cloud Integration
# ============================================
cloud:
  # Enable automatic cloud photo sync?
  enabled: false
  
  # Cloud service
  # Options: dropbox, google_photos, onedrive, nextcloud
  service: "dropbox"
  
  # Cloud folder path
  folder: "/Photos/PictureFrame"
  
  # Sync interval (seconds)
  # 3600 = hourly, 86400 = daily
  sync_interval: 3600
  
  # Delete local photos if removed from cloud?
  sync_deletions: false
  
  # Credentials file (created during setup)
  credentials_file: "/home/pi/.picture_frame_cloud_auth"

# ============================================
# Performance & Optimization
# ============================================
performance:
  # Preload next image while displaying current?
  # Reduces transition time but uses more memory
  preload_next: false
  
  # Number of images to keep in memory cache
  # 0 = disabled, higher = faster but more RAM
  cache_size: 0
  
  # Thumbnail generation for faster preview?
  generate_thumbnails: false
  
  # Thumbnail directory
  thumbnail_dir: "/home/pi/.picture_frame_cache"

# ============================================
# Error Handling
# ============================================
error_handling:
  # What to do if an image fails to load?
  # Options: skip, show_error, retry
  on_load_failure: "skip"
  
  # Number of retry attempts
  retry_attempts: 3
  
  # Show error message on display?
  display_errors: false
  
  # Continue running if no images found?
  # false = exit, true = wait and retry
  continue_on_empty: true
  
  # Retry interval when no images (seconds)
  empty_retry_interval: 60

# ============================================
# Development / Debug
# ============================================
development:
  # Simulation mode (don't require actual hardware)
  simulation_mode: false
  
  # Save processed images to disk for inspection?
  save_processed: false
  
  # Processed image output directory
  processed_output: "/home/pi/processed_frames"
  
  # Verbose image processing logs?
  verbose_processing: false
  
  # Enable performance profiling?
  enable_profiling: false